"""Markdown report generator — the client deliverable."""

from __future__ import annotations

from datetime import date
from typing import Iterable

from .niche_analyzer import NicheReport
from .types import ArbitrageOpportunity, EdgeScore


def _fmt_pct(x: float) -> str:
    return f"{x * 100:.1f}%"


def _emoji(score: float) -> str:
    """ASCII tier marker — no real emoji to stay terminal-safe."""
    if score >= 0.65:
        return "[A]"
    if score >= 0.45:
        return "[B]"
    if score >= 0.25:
        return "[C]"
    return "[D]"


def render_arbitrage_section(opps: Iterable[ArbitrageOpportunity]) -> str:
    lines = ["## Top arbitrage opportunities", ""]
    lines.append("| # | Topic | Source -> Target | Score | EV | Difficulty |")
    lines.append("|---|---|---|---|---|---|")
    for i, o in enumerate(opps, 1):
        lines.append(
            f"| {i} | {o.topic} | {o.source_platform} -> {o.target_platform} "
            f"| {_emoji(o.score)} {o.score:.2f} | {o.expected_value:.2f} | {o.difficulty:.2f} |"
        )
    lines.append("")
    lines.append("### Rationale")
    for i, o in enumerate(opps, 1):
        lines.append(f"{i}. **{o.topic}** — {o.rationale}")
    lines.append("")
    return "\n".join(lines)


def render_niche_section(report: NicheReport) -> str:
    lines = [f"## Niche overview: `{report.niche}`", ""]
    lines.append("| Platform | Topics | Avg engagement | Total supply | Saturation |")
    lines.append("|---|---|---|---|---|")
    for s in report.summaries:
        lines.append(
            f"| {s.platform} | {s.topic_count} | {_fmt_pct(s.avg_engagement)} "
            f"| {s.total_supply} | {s.saturation} |"
        )
    lines.append("")
    lines.append(
        f"**Recommended SOURCE platforms** (proven demand): "
        + ", ".join(report.recommended_source_platforms or ("none",))
    )
    lines.append(
        f"**Recommended TARGET platforms** (under-supplied): "
        + ", ".join(report.recommended_target_platforms or ("none",))
    )
    lines.append("")
    return "\n".join(lines)


def render_edge_section(handle: str, score: EdgeScore) -> str:
    lines = [f"## Edge audit: `{handle}`", ""]
    lines.append(f"**Overall edge score:** {_emoji(score.overall)} **{score.overall:.2f} / 1.00**")
    lines.append("")
    lines.append("| Component | Score | Weight |")
    lines.append("|---|---|---|")
    w = EdgeScore.weights()
    for k, label in [
        ("vocabulary_uniqueness", "Vocabulary uniqueness"),
        ("topic_concentration",   "Topic concentration"),
        ("audience_cohesion",     "Audience cohesion"),
        ("engagement_depth",      "Engagement depth"),
        ("hook_repeatability",    "Hook repeatability"),
    ]:
        val = getattr(score, k)
        lines.append(f"| {label} | {val:.2f} | {_fmt_pct(w[k])} |")
    lines.append("")
    lines.append(f"**Verdict:** {score.verdict}")
    lines.append("")
    return "\n".join(lines)


def render_full_report(
    *,
    client_name: str,
    niche_report: NicheReport,
    opportunities: list[ArbitrageOpportunity],
    edge_handle: str | None = None,
    edge_score: EdgeScore | None = None,
) -> str:
    today = date.today().isoformat()
    parts = [
        f"# PICKAXE-EDGE report — {client_name}",
        f"_Generated {today}_",
        "",
        "## Executive summary",
        "",
    ]
    if opportunities:
        top = opportunities[0]
        parts.append(
            f"Top opportunity: **{top.topic}** — move from `{top.source_platform}` "
            f"to `{top.target_platform}` (EV {top.expected_value:.2f}, difficulty {top.difficulty:.2f})."
        )
    else:
        parts.append("No arbitrage opportunities found above the demand floor in this niche.")
    parts.append("")
    parts.append(render_niche_section(niche_report))
    if opportunities:
        parts.append(render_arbitrage_section(opportunities))
    if edge_handle and edge_score is not None:
        parts.append(render_edge_section(edge_handle, edge_score))
    parts.append("---")
    parts.append("_This report was generated by PICKAXE-EDGE. Re-run weekly — platforms shift fast._")
    return "\n".join(parts)
